package com.mimswright.sync
{
	/**
	 * An error generated by a parser when the input data could not be parsed.
	 * 
	 * @todo - move to as3lib
	 */
	public class ParseError extends Error
	{
		public static const NO_DATA:String = "The input object containes no data.";
		public static const MALFORMED_DATA:String = "The input object contains malformed data.";
		public static const GENERIC:String = "The input object could not be parsed."; 
		
		public function ParseError(message:String="", id:int=0)
		{
			super(message, id);
		}
		
	}
}